# Generated by Django 5.0.4 on 2024-04-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=50)),
                ('Organisation', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Started', models.DateField(max_length=20)),
                ('Ended', models.DateField(default='Present', max_length=20)),
            ],
        ),
    ]
