# Generated by Django 5.0.4 on 2024-04-13 16:12

import autoslug.fields
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution', models.CharField(max_length=100)),
                ('Certificate', models.CharField(max_length=60)),
                ('Started', models.DateField(max_length=20)),
                ('Ended', models.DateField(default='Present', max_length=20)),
                ('Location', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='certificate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('started', models.DateField(max_length=20)),
                ('ended', models.DateField(default='Present', max_length=20)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='position', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(default='', max_length=50)),
                ('x', models.CharField(default='', max_length=50)),
                ('facebook', models.CharField(default='', max_length=50)),
                ('linkedIn', models.CharField(default='', max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='github')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstame', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('phone', models.IntegerField(default='+2348170371922')),
                ('country', django_countries.fields.CountryField(default='NG', max_length=2)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('Dob', models.DateField(null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='firstname')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
