# Generated by Django 5.0.4 on 2024-04-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstame',
            new_name='firstname',
        ),
    ]
