# Generated by Django 5.0.4 on 2024-04-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution', models.CharField(max_length=100)),
                ('Certificate', models.CharField(max_length=60)),
                ('Started', models.DateField(max_length=20)),
                ('Ended', models.DateField(default='Present', max_length=20)),
                ('Location', models.CharField(max_length=50)),
            ],
        ),
    ]
