# Generated by Django 5.0.4 on 2024-04-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website', models.CharField(default='', max_length=50)),
                ('X', models.CharField(max_length=50)),
                ('Facebook', models.CharField(default='', max_length=50)),
                ('LinkedIn', models.CharField(default='', max_length=50)),
                ('Github', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
